server {
    listen 80;
    server_name _;

    location /api/stakeholders/ {
        proxy_pass http://stakeholders:8080;
    }

    location /api/blog/ {
        proxy_pass http://blog:8081;
    }

    location /api/followers/ {
        proxy_pass http://follower:8082;
    }

    location = /api/tours {
        proxy_pass http://tours:8083/api/tours;
    }

    location /api/tours/ {
        proxy_pass http://tours:8083;
    }

    location /health/stakeholders {
        proxy_pass http://stakeholders:8080/health;
    }

    location /health/blog {
        proxy_pass http://blog:8081/health;
    }

    location /health/follower {
        proxy_pass http://follower:8082/health;
    }

    location /health/tours {
        proxy_pass http://tours:8083/health;
    }

    location / {
        proxy_pass http://front:80;
    }
}
