server {
    listen 80;
    server_name _;
    client_max_body_size 8m;

    location /api/stakeholders/ {
        proxy_pass http://stakeholders:8080;
    }

    location /api/blog/ {
        proxy_pass http://blog:8081;
    }

    location /api/followers/ {
        proxy_pass http://follower:8082;
    }

    location = /api/tours {
        proxy_pass http://tours:8083/api/tours;
    }

    location /api/tours/ {
        proxy_pass http://tours:8083;
    }

    location /api/payment/ {
        proxy_pass http://payment:8084;
    }

    location /health/stakeholders {
        proxy_pass http://stakeholders:8080/health;
    }

    location /health/blog {
        proxy_pass http://blog:8081/health;
    }

    location /health/follower {
        proxy_pass http://follower:8082/health;
    }

    location /health/tours {
        proxy_pass http://tours:8083/health;
    }

    location /health/payment {
        proxy_pass http://payment:8084/health;
    }

    location / {
        proxy_pass http://front:80;
    }
}

server {
    listen 50051 http2;
    server_name _;

    location /toursrpc.ToursRpcService/ {
        grpc_pass grpc://tours:9093;
    }
}
