spring.application.name=tours-service
server.port=${SERVER_PORT:8083}

spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/toursdb}

jwt.secret=${JWT_SECRET:change-me}
jwt.issuer=${JWT_ISSUER:stakeholders-service}
