server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /api/stakeholders/ {
        proxy_pass http://stakeholders:8080;
    }

    location /api/blog/ {
        proxy_pass http://blog:8081;
    }

    location /health {
        proxy_pass http://blog:8081/health;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
